from freqtrade_truth.adapters import (
    BybitApiKeySafetyError,
    BybitInverseClosedPnlAdapter,
    BybitInverseMarketInfo,
    BybitInverseTransactionLogReader,
    BybitMarketPreflightError,
    BybitResponseError,
    BybitTransactionLogEntry,
    BybitTransactionLogError,
    BybitTransactionLogQuery,
    BybitV5HmacTransport,
    BybitV5PublicTransport,
    FreqtradeReadAdapter,
    FreqtradeResponseError,
    HttpTransportError,
    JsonHttpTransport,
    ReadOnlyTradeAdapter,
    RetryingJsonTransport,
    StdlibJsonTransport,
    list_bybit_inverse_trading_symbols,
    verify_bybit_inverse_perpetual,
    verify_bybit_read_only_key,
)


def test_preview_public_adapter_api_is_importable() -> None:
    exported = {
        BybitApiKeySafetyError,
        BybitInverseClosedPnlAdapter,
        BybitInverseMarketInfo,
        BybitInverseTransactionLogReader,
        BybitMarketPreflightError,
        BybitResponseError,
        BybitTransactionLogEntry,
        BybitTransactionLogError,
        BybitTransactionLogQuery,
        BybitV5HmacTransport,
        BybitV5PublicTransport,
        FreqtradeReadAdapter,
        FreqtradeResponseError,
        HttpTransportError,
        JsonHttpTransport,
        ReadOnlyTradeAdapter,
        RetryingJsonTransport,
        StdlibJsonTransport,
        list_bybit_inverse_trading_symbols,
        verify_bybit_inverse_perpetual,
        verify_bybit_read_only_key,
    }

    assert len(exported) == 21
